FROM danteev/texlive:<% switch (texlive) {
  case 2025: %>edge<% break;
  case 2024: %>2024-B<% break;
  case 2023: %>2023-A<% break;
  // 2022 does not exist - see https://github.com/dante-ev/docker-texlive/blob/main/CHANGELOG.md
  case 2021: %>2021-D<% break;
} -%>

WORKDIR /workdir

COPY . /workdir

RUN latexmk <%= filenames.main %>
