FROM danteev/texlive:<% switch (texlive) {
  case 2019: %>2019-A<% break;
  case 2020: %>2020-A<% break;
  case 2021: %>edge<% break;
} -%>

WORKDIR /workdir

COPY . /workdir

RUN latexmk <%= filenames.main %>
