FROM registry.gitlab.com/islandoftex/images/texlive:<% switch (texlive) {
  case 2025: %>latest<% break;
  case 2024: %>TL2024-historic<% break;
  case 2023: %>TL2023-historic<% break;
} -%>

WORKDIR /workdir
