FROM danteev/texlive:<% switch (texlive) {
  case 2023: %>edge<% break;
  // 2022 does not exist - see https://github.com/dante-ev/docker-texlive/blob/main/CHANGELOG.md
  case 2021: %>2021-D<% break;
} -%>

WORKDIR /workdir

COPY . /workdir

RUN latexmk <%= filenames.main %>
