name: Check
on:
  push:
  schedule:
    - cron: "5 6 * * 1"
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  pdf:
    name: pdf (latexmk <%= filenames.main %>)
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: '${{ github.workspace }}/Texlivefile'
      - name: Prepare latexmk
        run: |
          updmap -sys
          texhash
          tlmgr generate language --rebuild-sys
          if [ ! -f "latexmkrc" ]; then
            cp "_latexmkrc" "latexmkrc"
          fi
      - run: latexmk <%= filenames.main %>
<% if (githubpublish || (lang == "en") && (reallatexcompiler.startsWith("lualatex"))) { -%>

      # Highlight mis-spelled words in the PDF
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: aspell aspell-en<% if (githubpublish || (language == 'de')) { %> aspell-de<% } %>
          version: 1.0
          execute_install_scripts: true
      - name: aspell
        run: |
          for tex in $(ls *.tex content/*.tex 2>/dev/null); do
            # The lualatex package "spelling" requires the content to be in a file ending with ".spell.bad"
            aspell --mode=tex <% if (language == 'de') { %>-l de_DE --run-together<% } else { %>-l en_US<% } %> --encoding=utf-8 --conf=./.aspell.conf -p ./.aspell.en.pws list < $tex | sort | uniq >> <%= filenames.main %>.spell.bad
          done
      - run: latexmk <%= filenames.main %>

      - name: Job summary using texlogsieve
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          texlogsieve <%= filenames.main %>.log | tee -a "$GITHUB_STEP_SUMMARY" || true
          echo '```' >> $GITHUB_STEP_SUMMARY
<% } -%>
      - uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: |
            <%= filenames.main %>.pdf
            <%= filenames.main %>.log
            <%= filenames.main %>.fls
  word-count:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: '${{ github.workspace }}/Texlivefile'
          texlive_version: <%= texlive %>
      - name: Count words
        run: |
          texcount -utf8 -inc <%= filenames.main %>.tex > texcount.txt
          echo "## TeXcount word count" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat "texcount.txt" >> $GITHUB_STEP_SUMMARY

          texcount -utf8 -inc -v -html <%= filenames.main %>.tex > texcount.html

          # output for summary
          # too verbose - therefore disabled
          #
          # texcount -utf8 -inc -v -htmlcore <%= filenames.main %>.tex > texcount.html-body
          # echo "" >> $GITHUB_STEP_SUMMARY
          # echo "## TeXcount LaTeX interpretation" >> $GITHUB_STEP_SUMMARY
          # echo "" >> $GITHUB_STEP_SUMMARY
          # cat "texcount.html-body" >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
          name: word-count
          path: |
            texcount.txt
            texcount.html
  spell-check:
    # This is based on https://github.com/mh61503891/action-paper-aspell/tree/master
    #
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Original action does not work well - see https://github.com/awalsh128/cache-apt-pkgs-action/pull/136
      # The action is not updated - and thus the dictionaries are not updated
      - uses: bscott-zebra/cache-apt-pkgs-action@avoid_using_xargs
        with:
          packages: aspell aspell-en<% if (language == 'de') { %> aspell-de<% } %>
          version: 1.0
          execute_install_scripts: true

      - name: aspell
        run: |
          echo "| file | status |" >> $GITHUB_STEP_SUMMARY
          echo "| -- | -- |" >> $GITHUB_STEP_SUMMARY
          failure=0
          for tex in $(ls *.tex content/*.tex 2>/dev/null); do
            # Words are output in the order they appear in the document
            words=$(aspell --mode=tex <% if (language == 'de') { %>-l de_DE --run-together<% } else { %>-l en_US<% } %> --encoding=utf-8 --conf=./.aspell.conf -p ./.aspell.en.pws list < $tex | tr '\n' ' ')
            if [ -z "$words" ]; then
              echo "| $tex | ✅ |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| $tex | ❌ $words |" >> $GITHUB_STEP_SUMMARY
              if [[ "$tex" == "<%= filenames.main %>.tex" ]]; then
                failure=1
              fi
            fi
          done
          if [[ "$failure" -eq 1 ]]; then
             echo "" >> $GITHUB_STEP_SUMMARY
             echo 'If you want to ignore words, add them to `.aspell.en.pws` (your personal aspell dictionary)' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
  indent:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: bscott-zebra/cache-apt-pkgs-action@avoid_using_xargs
        with:
          packages: libyaml-tiny-perl libfile-homedir-perl
          version: 1.0
          execute_install_scripts: true
      - name: Install latexindent
        uses: zauguin/install-texlive@v4
        with:
          packages: latexindent
          texlive_version: <%= texlive %>
      - run: make format
      - name: No changes made by latexindent
        run: git diff --exit-code
