name: Check docker images
on:
  schedule:
    - cron: "0 6 * * 5"
  push:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.eslintignore'
      - '.gitpod.dockerfile'
      - '.gitpod.yml'
      - '.gitattributes'
      - '.gitignore'
      - '.markdownlint.yml'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'generate-texlivefile.sh'
      - 'LICENSE'
      - 'README.md'
      - 'setup-do.sh'
      - 'user-data.sh'
      - 'docs/**'
      - '.vscode/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.eslintignore'
      - '.gitpod.dockerfile'
      - '.gitpod.yml'
      - '.gitattributes'
      - '.gitignore'
      - '.markdownlint.yml'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'generate-texlivefile.sh'
      - 'LICENSE'
      - 'README.md'
      - 'setup-do.sh'
      - 'user-data.sh'
      - 'docs/**'
      - '.vscode/**'
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.actor_id }}
  cancel-in-progress: true
jobs:
  check-reitzig:
    name: Create reitzig
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          path: 'code'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'code/package-lock.json'
      - run: npm ci
        working-directory: ${{ github.workspace }}/code
      - run: npm install -g yo
      - name: Create lncs-reitzig
        run: yo ${{ github.workspace }}/code/generators/app/index.js --documentclass=lncs --papersize=a4 --latexcompiler=pdflatex --bibtextool=bibtex --texlive=2024 --docker=reitzig --overleaf=no --lang=en --font=default --listings=minted --enquotes=csquotes --tweakouterquote=babel --todo=pdfcomment --examples=true --howtotext=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          context: .
          tags: localhost:5000/name/app:latest
      - run: mkdir /tmp/out
      - name: Build paper.tex
        run: docker run -v $(pwd):/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "latexmk paper.tex"
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: /tmp/out
  check-iot-dante:
    runs-on: ubuntu-latest
    name: Create ${{ matrix.docker }}
    strategy:
      matrix:
        docker: ["iot", "dante"]
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          path: 'code'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'code/package-lock.json'
      - run: npm ci
        working-directory: ${{ github.workspace }}/code
      - run: npm install -g yo
      - name: Create lncs-${{ matrix.docker }}
        run: yo ${{ github.workspace }}/code/generators/app/index.js --documentclass=lncs --papersize=a4 --latexcompiler=pdflatex --bibtextool=bibtex --texlive=2024 --docker=${{ matrix.docker }} --overleaf=no --lang=en --font=default --listings=minted --enquotes=csquotes --tweakouterquote=babel --todo=pdfcomment --examples=true --howtotext=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          context: .
          tags: localhost:5000/name/app:latest
      - name: Build paper.tex
        run: docker run -v $(pwd):/workdir localhost:5000/name/app:latest latexmk paper.tex
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: /workdir/paper.pdf
