name: LNCS pdflatex
on: [push]
jobs:
  bibtex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [en, de]
        font: [default, times]
        cleveref: [true, false]
        enquotes: [csquotes, textcmds, plainlatex]
        examples: [true, false]
        todo: [pdfcomment, none]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - name: Generate template
        run: |
          mkdir tmp && cd tmp
          npx yo $GITHUB_WORKSPACE\
           --documentclass=lncs\
           --latexcompiler=pdflatex\
           --bibtextool=bibtex\
           --texlive=tl2019\
           --language==${{ matrix.language }} --font=${{ matrix.font }}\
           --cleveref=${{ matrix.cleveref }} --enquotes=${{ matrix.enquotes }}\
           --todo=${{ matrix.todo }}\
           --examples=${{ matrix.examples }}
          pwd
          ls -la
        env:
          yeoman_test: true
      - name: latexmk
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
          # ${{ github.workspace }} holds wrong directory (only valid for "run" tasks, not for container-based tasks)
          working_directory: '/github/workspace/tmp'
  biblatex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [en, de]
        font: [default, times]
        cleveref: [true, false]
        enquotes: [csquotes, textcmds, plainlatex]
        examples: [true, false]
        todo: [pdfcomment, none]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - name: Generate template
        run: |
          mkdir tmp && cd tmp
          npx yo $GITHUB_WORKSPACE\
           --documentclass=lncs\
           --latexcompiler=pdflatex\
           --bibtextool=biblatex\
           --texlive=tl2019\
           --language==${{ matrix.language }} --font=${{ matrix.font }}\
           --cleveref=${{ matrix.cleveref }} --enquotes=${{ matrix.enquotes }}\
           --todo=${{ matrix.todo }}\
           --examples=${{ matrix.examples }}
          pwd
          ls -la
        env:
          yeoman_test: true
      - name: latexmk
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
          # ${{ github.workspace }} holds wrong directory (only valid for "run" tasks, not for container-based tasks)
          working_directory: '/github/workspace/tmp'
