name: Tests
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Run Jest tests
        uses: stefanoeb/jest-action@master
